#!/usr/bin/env bash
# A bash crits that installs Nginx

apt-get -y update
apt-get -y install nginx
echo "Hello world!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/TG199 permanent;/" /etc/nginx/sites-available/default
service nginx start
