#!/usr/bin/env bash
# Write a Bash script that 1 Creates the file /var/run/myscript.pid containing its PID 2 Displays To infinity and beyond indefinitely 3 Displays I hate the kill command when receiving a SIGTERM signal 4 Displays Y U no love me?! when receiving a SIGINT signal 5 Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
