#!/usr/bin/env bash
# A FizzBuZZ scripts

i=1

while [ $i -ne 100 ]
do
	if [[ $((i % 3)) -eq 0 ]] && [[ $((i % 5)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	(( i++ ))
done

