#!/usr/bin/env bash
# displays numbers 1 - 20
i="1"
while [ $i -ne 21 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from china"
			;;
		9)
			echo "$i"
			echo "bad luck from japan"
			;;
		17)
			echo "$i"
			echo "bad luck from italy"
			;;
		*)
			echo "$i"
			;;
	esac
	i=$((i+1))

done
