#!/usr/bin/env bash
# displays numbers 1 - 20
i="1"
while [ $i -ne 21 ]
do
	case $i in
		"4")
			echo "4"
			echo "bad luck from china"
			;;
		"9")
			echo "9"
			echo "bad luck from japan"
			;;
		"17")
			echo "17"
			echo "bad luck from italy"
			;;
		*)
			echo "$i"
			;;
	esac
	i=$((i+1))

done
